sonar.projectKey=Angular.web
sonar.projectName=Angular.web
sonar.projectVersion=1.0

sonar.sources=angular.web/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/test-results/**,**/*.spec.ts
sonar.tests=angular.web/src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=angular.web/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=angular.web/coverage/cobertura-coverage.xml
